### ISSUE TITLE
About the computation for CIFAR10 experiment

### ISSUE THREAD

**Issue by momo1986** [locuslab/robust_overfitting#3]
Hello,

Thanks for your sharing and your outstanding contributions for adversarial learning.

I wonder how much computation power is needed to run the default settings of CIFAR10, e.g., batch_size=128.

Could you list the corresponding GPU architectures which is able to run it? How many GPU memories are needed.

Thanks & Regards!
Momo

**Comment by riceric22** [comment]
Hi Momo, 

The requirements for the CIFAR10 experiments will vary based on the architecture. The ResNet18 architecture used in the majority of the paper can very easily fit on one GPU, whereas the Wide ResNets trained in the double descent experiment needed up to four GPUs (we used 1080tis). 

~Eric
